"""firebase auth migration

Revision ID: 4550c83dcfc1
Revises: d316931312e6
Create Date: 2026-05-07 15:01:18.766945

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4550c83dcfc1'
down_revision: Union[str, None] = 'd316931312e6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('firebase_uid', sa.String(), nullable=False))
    op.add_column('user', sa.Column('auth_provider', sa.String(), nullable=True))
    op.create_unique_constraint(None, 'user', ['email'])
    op.create_unique_constraint(None, 'user', ['firebase_uid'])
    op.drop_column('user', 'hash_password')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('hash_password', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'user', type_='unique')
    op.drop_constraint(None, 'user', type_='unique')
    op.drop_column('user', 'auth_provider')
    op.drop_column('user', 'firebase_uid')
    # ### end Alembic commands ###
